# OLÃ, RAMON AQUI âš¡!
- ğŸ”­ Visando trabalhar em front-and
- ğŸŒ± estudando HTML,CSS e JS
- ğŸ˜„ Pronouns: ELE/DELE

##
<div align="center">
  <a href="https://github.com/rXavier-L">
  <img height="160em" src="https://github-readme-stats.vercel.app/api?username=rXavier-L&show_icons=true&theme=react&include_all_commits=true&count_private=true"/>
  <img height="160em" src="https://github-readme-stats.vercel.app/api/top-langs/?username=rXavier-L&layout=compact&langs_count=7&theme=react"/>
</div>
  <br>
  <div  align="center"> 
<div style="display: inline_block"><br>
 <img align="center" alt="Xavier-Js" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-plain.svg">
 <img align="center" alt="Xavier-HTML" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg">
 <img align="center" alt="Xavier-CSS" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg">
 <img align="center" alt="Xavier-Python" height="30" width="40" src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg">
    <img align="right" alt="Rafa-pic" height="200" style="border-radius:50px;"
         src="https://media.giphy.com/media/tDFuZ1Pq8bCxxD59bR/giphy.gif">
  </div>
  
  ##
  
  <div>
    <a href="https://www.instagram.com/x_de_cha/" target="_blank"><img src="https://img.shields.io/badge/-Instagram-%23E4405F?style=for-the-badge&logo=instagram&logoColor=white" target="_blank"></a>
   <a href="https://discord.gg/ZwmG39Sa" target="_blank"><img src="https://img.shields.io/badge/Discord-7289DA?style=for-the-badge&logo=discord&logoColor=white" target="_blank"></a> 
   <a href = "mailto:contato=ramonxavierleal@gmail.com"><img src="https://img.shields.io/badge/-Gmail-%23333?style=for-the-badge&logo=gmail&logoColor=white" target="_blank"></a>
   <a href="https://www.linkedin.com/in/ramon-xavier-8a4248229/" target="_blank"><img src="https://img.shields.io/badge/-LinkedIn-%230077B5?style=for-the-badge&logo=linkedin&logoColor=white" target="_blank"></a>
    
    
  ![Snake animation](https://github.com/rXavier-L/rXavier-L/blob/output/github-contribution-grid-snake.svg)  
    
  </div>
